nodeLinker: node-modules

npmRegistryServer: https://registry.yarnpkg.com

yarnPath: .yarn/releases/yarn-4.1.1.cjs
httpProxy: "http://proxy.jpmchase.net:8443"
httpsProxy: "http://proxy.jpmchase.net:8443"