const contentTokensOnboardingEng: Record<string, string | string[]> = {
  'common.validCharacters': "-_.,'+/?%&()[]",
  'common.numbersStartFirst': '(!) Address must start with numbers',
  'common.line2Empty':
    '(!) Address Line 3 must be empty if Address Line 2 is empty',
  'common.addressValidCharacters': "-.,'/&#@%",
  'common.invalidCharactersErrorMessage':
    '(!) Invalid characters. Please use only letters, numbers, and allowed characters ',
  'common.startWithNumber': 'Address has to start with a number',
  'common.justDigits': '(!) Address is incomplete',

  // START - Common Components
  'components.myDataGrid.errorMessage': 'Data fetching error',
  'components.myDataGrid.emptyMessage': 'No data is available.',
  'components.myDataGrid.emptyTitle': 'No data',
  'components.myDataGrid.refreshActionLabel': 'Click to refresh',

  // START - Common DataTableGrid
  'components.DataTableGrid.errorMessage': 'Data fetching error',
  'components.DataTableGrid.emptyMessage': 'No data is available.',
  'components.DataTableGrid.emptyTitle': 'No data',
  'components.DataTableGrid.refreshActionLabel': 'Click to refresh',
  'components.DataTableGrid.description': `You can sort the list of transactions or use filters to review the information you are most interested in. All date and time values are displayed in browser timezone {word}`,
  'components.DataTableGrid.smDescription': `All date and time values are displayed in browser timezone {word}`,
  // ---------
  'components.DataTableGrid.DataTableGridFilterHeader.searchRange': `Last 7 days`,
  'components.DataTableGrid.DataTableGridFilterHeader.searchRangePlaceholder': `filter by`,
  'components.DataTableGrid.DataTableGridFilterHeader.searchRangeList': `All Transactions,Current day,Previous day,Last 7 days,Last 14 days,Last 30 days,Last 2 months,Last 3 months,Last 6 months,Last 12 months,Last 24 months`,
  'components.DataTableGrid.DataTableGridFilterHeader.transactionSearchHeader': `To refine your view sort the data in alphabetical or numerical order or use column filters to refine the data you want to see.`,
  'components.DataTableGrid.DataTableGridFilterHeader.searchTransactionBy': `Quick filter`,
  'components.DataTableGrid.DataTableGridFilterHeader.clear': `Reset filters`,
  'components.DataTableGrid.DataTableGridFilterHeader.filterApplied': `Filters applied:`,
  'components.DataTableGrid.DataTableGridFilterHeader.apply': `Advanced filters`,
  'components.DataTableGrid.DataTableGridFilterHeader.custom': `Custom`,
  'components.DataTableGrid.DataTableGridFilterHeader.all': `ALL`,

  // ---------
  'components.DataTableGrid.SearchHeaderFilterModal.title': `Filters`,
  // ---------
  // ---------
  'components.DataTableGrid.DataTableGridTopFilter.display': `Display for:`,
  // ---------
  'components.DataTableGrid.DataTableGridFilterGenerated.searchText': `Search by any of these transaction details.`,
  'components.DataTableGrid.DataTableGridFilterGenerated.close': `Cancel`,
  'components.DataTableGrid.DataTableGridFilterGenerated.reset': `Reset`,
  'components.DataTableGrid.DataTableGridFilterGenerated.apply': `Apply`,
  // ---------
  'components.alertMessage.errorTitleSuccess': 'Success',
  // ------- BirthdayPicker
  'components.CustomDatePicker.label': 'Date of birth',
  'components.CustomDatePicker.month': 'Month',
  'components.CustomDatePicker.day': 'Day',
  'components.CustomDatePicker.year': 'Year',
  'components.CustomDatePicker.placeHolder': 'Pick a date',
  'components.CustomDatePicker.clear': 'Clear the date',
  // ------- BackLink
  'components.BackLink.backLinkLabel': 'Back',
  // ------- ContextualHelp
  'components.ContextualHelp.avatarHelp': 'get help',
  'components.ContextualHelp.questionText': 'How can I help today?',
  'components.ContextualHelp.navLinkLabel': 'Take an experience tour',
  'components.ContextualHelp.navLinkLabelFAQ': `... or explore the whole FAQ section`,
  'components.ContextualHelp.supportNumberBasic': `(866) 251-0588`,
  'components.ContextualHelp.supportNumberIntl': `(212) 622-9814`,
  // ------- DashboardWidget
  'components.DashboardWidget.title': `No title`,
  // ------- EinInput
  'components.EinInput.label': `Employer Identification Number`,
  // ------- BasicDataLoadingError
  'components.BasicDataLoadingError.alertDataErrTitle': `Something went wrong ...`,
  'components.BasicDataLoadingError.errorText': `Error loading data. Please try again later, or refresh the page.`,
  // ------- BasicDataLoadingError
  'components.BasicEmptyState.title': `No data`,
  'components.BasicEmptyState.text': ` `,
  // ------- Layout
  'components.Layout.NavText': `No business name`,
  'components.Layout.NavTextNo': `No client ID`,
  'components.Layout.NavLoading': `loading ...`,
  'components.Layout.openNavigation': `Open navigation`,
  'components.Layout.closeNavigation': `Close navigation`,
  'components.Layout.skipToNavigation': `Skip to Navigation`,
  'components.Layout.skipToMainContent': `Skip to Main Content`,
  // --------
  'components.Layout.UserName': `Unnamed user`,
  'components.Layout.UserEmail': `No email found`,
  'components.Layout.ADALabels.UserMenu': `User menu`,
  'components.Layout.ADALabels.UserAvatar': `User avatar`,
  // --------
  'components.Layout.MenuLabel': `Account`,
  'components.Layout.MenuItem': `Log out`,
  // --------
  'components.Layout.TextBy': ``,
  // --------
  'components.Layout.linkDashboard': `Dashboard`,
  'components.Layout.linkTransactions': `Transactions`,
  'components.Layout.linkMakePay': `Make a payment`,
  'components.Layout.linkAccounts': `Accounts`,
  'components.Layout.linkDebit': `Debit Card`,
  'components.Layout.linkRecipients': `Recipients`,
  'components.Layout.linkRecipientsExternalAccount': `Recipients & External Account`,
  'components.Layout.linkLinkedAccount': `External Account`,
  'components.Layout.linkStatements': `Statements`,
  'components.Layout.linkSupport': `Support`,
  'components.Layout.linkBusiness': `Business details`,
  'components.Layout.linkNoClientIdLinks': `Onboarding`,
  // ------- ServerStateOverlays
  'components.ServerStateOverlays.AlertTitle': `Loading ...`,
  'components.ServerStateOverlays.Title': `No {word} found`,
  // ------- PersonCard
  'components.PersonCard.name': `Name`,
  // -------
  'components.PersonCard.cardName': `Name`,
  'components.PersonCard.addressLine1': `AddressLine1`,
  'components.PersonCard.addressLine2': `AddressLine2`,
  'components.PersonCard.addressLine3': `AddressLine3`,
  'components.PersonCard.zip': `State_Zip_Country`,
  'components.PersonCard.email': `Email`,
  // -------
  'components.PersonCard.birthDate': `DOB:`,
  'components.PersonCard.phoneNumber': `Phone:`,
  // ------- PhoneInput
  'components.PhoneInput.phoneNumber': `Phone number`,
  // ------- Ssn4Input
  'components.Ssn4Input.ssn': `Social Security Number`,
  // ------- UsStateSelect
  'components.UsStateSelect.state': `State`,
  'components.UsStateSelect.selectState': `Select state`,
  // END - Common Components

  // START - Page Onboarding
  'pages.OnboardingPage.reviewInProgressTitle': `Thank you for submitting your additional details.`,
  'pages.OnboardingPage.reviewInProgressLine1': `We are processing your application and will contact you once complete.`,
  'pages.OnboardingPage.reviewInProgressLine2': `If you need further assistance contact the J.P. Morgan Embedded Banking team`,
  'pages.OnboardingPage.callus': `Call us anytime {word}`,
  'pages.OnboardingPage.fetch': `Fetching onboarding status`,
  'pages.OnboardingPage.errorBoundText': `Unexpected error`,
  'pages.OnboardingPage.errorButtonText': `Try again`,
  'pages.OnboardingPage.alertTitle': `Complete Onboarding`,
  'pages.OnboardingPage.alertTextMsg': `We need some supplemental information from you before you can get started.`,
  'pages.OnboardingPage.alertTextMsg1': `If you have any queries, please contact us at {word}, Int’l: {word1}`,
  'pages.OnboardingPage.pageOnboardingWrapperTitle': `Account Application - Supplemental Information`,
  // END - Page Onboarding

  // START -  OnboardingWizard
  'features.OnboardingWizard.onboardingInit': `Onboarding Initiation`,
  'features.OnboardingWizard.wizardErrorTitle': `Something happened`,
  'features.OnboardingWizard.wizardError': `Failed to get verifications data`,
  'features.OnboardingWizard.clientVerification': `Clients Verifications Error: {word}`,
  'features.OnboardingWizard.clientUpdateError': `Clients Update Error: {word}`,
  'features.OnboardingWizard.alertMessageTitle': `There was an error trying to fetch your data.`,
  'features.OnboardingWizard.alertMessageText': `Please refresh the page or try again later. Contact us if the issue persists.`,
  'features.OnboardingWizard.lastStep': `This is the last step!`,
  'features.OnboardingWizard.Next': `Next: {word}`,
  'features.OnboardingWizard.buttonBack': `Back`,
  'features.OnboardingWizard.buttonIsLast': `Submit`,
  'features.OnboardingWizard.buttonIsNext': `Next`,
  'features.OnboardingWizard.activeStepper': `Stepper Clickable`,
  'features.OnboardingWizard.inactiveStepper': `Stepper Disabled`,
  'features.OnboardingWizard.ofSteps': `Onboarding Steps: `,
  'features.OnboardingWizard.validationErrorText': `Please check possible validation errors or missing values in the fields above`,
  // --- Steps Navigation Labels
  'features.OnboardingWizard.Business': `Business`,
  'features.OnboardingWizard.BusinessOwners': `Business Owners`,
  'features.OnboardingWizard.Controller': `Personal`,
  'features.OnboardingWizard.DecisionMakers': `Decision Makers`,
  'features.OnboardingWizard.AdditionalDetails': 'Additional Info',
  'features.OnboardingWizard.Review': `Review`,
  'features.OnboardingWizard.Verifications': `Verifications`,

  // END - OnboardingWizard

  // START -  EntityTypeForm
  // -------- Schema
  'features.EntityTypeForm.schemaLegal': `(!) Please select an entity type`,
  'features.EntityTypeForm.schemaAnswerQuestion': `(!) Please answer this question.`,
  // --------
  'features.EntityTypeForm.title': `What kind of business do you run?`,
  'features.EntityTypeForm.radioLabelLegal': `Please select a legal structure`,
  'features.EntityTypeForm.radioValue': `Corporation`,
  'features.EntityTypeForm.radioValueCorpLabel': `Business (Corporation)`,
  'features.EntityTypeForm.radioValueCorpDesc': `Your business is registered as a Corporation.`,
  'features.EntityTypeForm.radioValueLLC': `Limited Liability Company`,
  'features.EntityTypeForm.radioValueLLCLabel': `Business (LLC)`,
  'features.EntityTypeForm.radioValueLLCDesc': `Your business is registered as a Limited Liability Company.`,
  'features.EntityTypeForm.radioValueLP': `Limited Partnership`,
  'features.EntityTypeForm.radioValueLPLabel': `Business (LP)`,
  'features.EntityTypeForm.radioValueLPDesc': `Your business is registered as a Limited Partnership.`,
  'features.EntityTypeForm.radioValueSOLE': `Sole Proprietorship"`,
  'features.EntityTypeForm.radioValueSOLELabel': `Sole Proprietor`,
  'features.EntityTypeForm.radioValueSOLEDesc': `You are the sole owner of an incorporated business.`,
  'features.EntityTypeForm.corpText1': `The information we request from you will help us complete setting up your account.`,
  'features.EntityTypeForm.corpText2': `Please review and update any information that needs confirmation; and provide any additional information requested.`,
  'features.EntityTypeForm.corpText3': `As a privately owned business, make sure to confirm the following in the relevant sections:`,
  'features.EntityTypeForm.corpTextList': `
    Employer Identification Number (EIN),
    Controller's Contact Information,
    Controller's SSN,
    Controller's Date of Birth,
    All Owners' Contact Information,
    All Owners' SSNs,
    All Owners' Date of Birth,
    Any additional senior managers in the business
  `,
  'features.EntityTypeForm.selectText': `Select a legal structure to get started.`,
  'features.EntityTypeForm.soloText': `As a sole proprietor, make sure to confirm the following in the relevant sections:`,
  'features.EntityTypeForm.soloListText': `
    Employer Identification Number (EIN) or SSN,
    Your Contact Information,
    Your Date of Birth
  `,
  'features.EntityTypeForm.titleQ': `Additional Questions`,
  'features.EntityTypeForm.radioQLabel':
    'Do you have locations, sell goods or services, or have vendors or suppliers in countries or regions subject to comprehensive sanctions programs (Iran, North Korea, Cuba, Syria and the Crimea, Donetsk, Luhansk Regions of Ukraine), or work with Sanctioned Parties in Russia or Venezuela?',
  'features.EntityTypeForm.radioLabelYes': `Yes`,
  'features.EntityTypeForm.radioLabelNo': `No`,
  'features.EntityTypeForm.radioILabel': `Do you identify as a provider, owner, and/or operator of private ATM(s) and/or third Party ATM(s) activity?`,
  'features.EntityTypeForm.radioIsBusLabel': `Are there any entities (or non-individuals) in your ownership hierarchy?`,
  'features.EntityTypeForm.radioIsSigLabel': `Are there any individuals who own 25% or more of your company?`,
  'features.EntityTypeForm.alertMessage': `(!) We cannot accept your application`,
  'features.EntityTypeForm.alertMessageText': `(!) We cannot onboard entities with business activity related to Cuba, Iran, Syria, North Korea or Crimea.`,
  'features.EntityTypeForm.alertMessageText1': `(!) We cannot onboard entities that identify as a business relating to ATM(s)`,
  'features.EntityTypeForm.alertMessageText2': `(!) We cannot onboard entities with non-individuals in their hierarchy at this time.`,
  'features.EntityTypeForm.checkProdLabel': `Auto-fill forms with mock data`,
  'features.EntityTypeForm.buttonStart': `Get started!`,
  // END EntityTypeForm

  // START -  STEPS - BusinessDetailsStep
  'steps.BusinessDetailsStep.detailsSectionTitle': `Tell us about your business`,
  'steps.BusinessDetailsStep.businessName.label': `Name of Your Business`,
  'steps.BusinessDetailsStep.businessName.description': ``,
  'steps.BusinessDetailsStep.businessName.placeholder': `Your Business`,
  'steps.BusinessDetailsStep.solePropBusinessName.label': `Business Legal Name`,
  'steps.BusinessDetailsStep.solePropBusinessName.description': `Your personal name is the legal name of this sole proprietorship`,
  'steps.BusinessDetailsStep.solePropBusinessName.placeholder': `Your Personal Name`,
  'steps.BusinessDetailsStep.businessAliasName.label': `Business Alias (optional)`,
  'steps.BusinessDetailsStep.businessAliasName.placeholder': `Business Alias`,
  'steps.BusinessDetailsStep.solePropBusinessAliasName.label': `Doing Business As (DBA)`,
  'steps.BusinessDetailsStep.solePropBusinessAliasName.placeholder': `Doing Business As`,
  'steps.BusinessDetailsStep.solePropBusinessAliasName.description': `Name used to run your business that is different than your personal name`,
  'steps.BusinessDetailsStep.solePropBusinessIdentification.label': `How do you identify your business?`,
  'steps.BusinessDetailsStep.solePropBusinessIdentification.placeholder': `Select one`,
  'steps.BusinessDetailsStep.solePropBusinessIdentification.option.ein': `EIN (Employer Identification Number)`,
  'steps.BusinessDetailsStep.solePropBusinessIdentification.option.ssn': `SSN (Social Security Number)`,
  'steps.BusinessDetailsStep.businessDescription.label': `Business Description`,
  'steps.BusinessDetailsStep.businessDescription.placeholder': `Provide a brief description of the nature of your business.`,
  'steps.BusinessDetailsStep.businessEmail.label': `Business Email (optional)`,
  'steps.BusinessDetailsStep.businessEmail.placeholder': `Business Email`,
  'steps.BusinessDetailsStep.businessPhone.label': `Phone Number`,
  'steps.BusinessDetailsStep.businessWebsite.label': `Business Website`,
  'steps.BusinessDetailsStep.businessWebsite.description': `Website URL must start with https://www.`,
  'steps.BusinessDetailsStep.businessWebsite.placeholder': `Business Website`,
  'steps.BusinessDetailsStep.text.notAvailable': `N/A`, // TODO: Should replace common texts with global tokens
  'steps.BusinessDetailsStep.text.or': `OR`,
  'steps.BusinessDetailsStep.websiteNotAvailable.label': `My business does not have a website`,
  'steps.BusinessDetailsStep.countryOfFormation.label': `Country of Formation`,
  'steps.BusinessDetailsStep.yearOfFormation.label': `Year of Formation`,
  'steps.BusinessDetailsStep.yearOfFormation.placeholder': `YYYY`,
  'steps.BusinessDetailsStep.addressSectionTitle': `What is your business address?`,
  'steps.BusinessDetailsStep.businessAddressSameAsController.label': `My business address is the same as my personal address`,
  'steps.BusinessDetailsStep.businessAddress.label': `Business Address`,
  'steps.BusinessDetailsStep.businessAddressLine1.placeholder': `Address Line 1`,
  'steps.BusinessDetailsStep.businessAddressLine2.placeholder': `Address Line 2`,
  'steps.BusinessDetailsStep.businessAddressLine3.placeholder': `Address Line 3`,
  'steps.BusinessDetailsStep.businessCity.label': `City`,
  'steps.BusinessDetailsStep.businessCity.placeholder': `City`,
  'steps.BusinessDetailsStep.businessZipCode.label': `ZIP Code`,
  'steps.BusinessDetailsStep.businessZipCode.placeholder': `ZIP Code`,
  'steps.BusinessDetailsStep.industryCategory.label': `Industry Category`,
  'steps.BusinessDetailsStep.industryCategory.placeholder': `Select a category`,
  'steps.BusinessDetailsStep.industryCategory.nothingFoundInfoLabel': `Nothing found`,
  'steps.BusinessDetailsStep.industryType.label': `Industry Type`,
  'steps.BusinessDetailsStep.industryType.placeholder': `Select a type`,
  'steps.BusinessDetailsStep.industryType.nothingFoundInfoLabel': `Nothing found`,
  // END -  STEPS - BusinessDetailsStep

  // START -  STEPS - BusinessDetailsStep -- schema
  'schema.BusinessDetailsStep.businessName': `(!) Please provide a name for your business`,
  'schema.BusinessDetailsStep.businessEmail': `(!) Please provide a valid email for your business (e.g.: name@example.com)`,
  'schema.BusinessDetailsStep.ein': `(!) Please enter a valid EIN`,
  'schema.BusinessDetailsStep.einReq': `(!) Please provide your Employer Identification Number`,
  'schema.BusinessDetailsStep.yearOfFormationMin': `(!) Year of formation should be a valid 4 digit year after 1900`,
  'schema.BusinessDetailsStep.yearOfFormationMax': `(!) Year of formation cannot be in the future`,
  'schema.BusinessDetailsStep.yearOfFormationReq': `(!) Please provide your business's year of formation`,
  'schema.BusinessDetailsStep.websiteReq': `(!) Please enter a business website OR confirm that you do not have one.`,
  'schema.BusinessDetailsStep.websiteTest': `(!) Website URL must start with http://www. or https://www.`,
  'schema.BusinessDetailsStep.businessDescriptionReq': `(!) Please provide a description for your business`,
  'schema.BusinessDetailsStep.maxStringLengthAlert': `(!) Should be less than {word} characters`,
  'schema.BusinessDetailsStep.businessAddressLine1Req': `(!) Address Line 1 is required`,
  'schema.BusinessDetailsStep.addressInvalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters - . ' / & # @ % `,
  'schema.BusinessDetailsStep.invalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters . , _ ' + - / ! ? % ( )[ ] `,
  'schema.BusinessDetailsStep.invalidCharactersText': `(!) Invalid characters. Please use only letters, numbers, and allowed characters `,
  'schema.BusinessDetailsStep.validCharactersSet': `.,/\\-'+!?&@%_()[\\] `,
  'schema.BusinessDetailsStep.invalidWhiteSpaces': `(!) Please remove the leading and trialing white spaces.`,
  'schema.BusinessDetailsStep.invalidNewLine': `(!) Please remove new line`,
  'schema.BusinessDetailsStep.businessCity': `(!) City is required`,
  'schema.BusinessDetailsStep.validBusinessCity': `(!) Please provide a valid city name`,
  'schema.BusinessDetailsStep.businessState': `(!) State is required`,
  'schema.BusinessDetailsStep.businessZipCodeMatch': `(!) Please enter a valid ZIP Code`,
  'schema.BusinessDetailsStep.businessZipCodeReq': `(!) ZIP Code is required`,
  'schema.BusinessDetailsStep.businessPhoneMatch': `(!) Please enter a valid phone number`,
  'schema.BusinessDetailsStep.isPhoneUSValid': `(!) Please enter a valid US phone number`,
  'schema.BusinessDetailsStep.businessPhoneReq': `(!) Phone number is required`,
  'schema.BusinessDetailsStep.industryType': `(!) Please select an industry type`,
  'schema.BusinessDetailsStep.industryCategory': `(!) Please select an industry category`,
  // END -  STEPS - BusinessDetailsStep -- schema

  // START -  STEPS - SoleProprietorBusinessDetailsStep -- schema
  'schema.SoleProprietorBusinessDetailsStep.businessName': `(!) Please provide a name for your business`,
  'schema.SoleProprietorBusinessDetailsStep.ein': `(!) Please enter a valid EIN`,
  'schema.SoleProprietorBusinessDetailsStep.einReq': `(!) Please provide your Employer Identification Number`,
  'schema.SoleProprietorBusinessDetailsStep.yearOfFormationMin': `(!) Year of formation should be a valid 4 digit year after 1900`,
  'schema.SoleProprietorBusinessDetailsStep.yearOfFormationMax': `(!) Year of formation cannot be in the future`,
  'schema.SoleProprietorBusinessDetailsStep.yearOfFormationReq': `(!) Please provide your business's year of formation`,
  'schema.SoleProprietorBusinessDetailsStep.websiteReq': `(!) Please enter a business website OR confirm that you do not have one.`,
  'schema.SoleProprietorBusinessDetailsStep.websiteTest': `(!) Website URL must start with http://www. or https://www.`,
  'schema.SoleProprietorBusinessDetailsStep.businessDescriptionReq': `(!) Please provide a description for your business`,
  'schema.SoleProprietorBusinessDetailsStep.businessAddressLine1Req': `(!) Address Line 1 is required`,
  'schema.SoleProprietorBusinessDetailsStep.maxStringLengthAlert': `(!) Should be less than {word} characters`,
  'schema.SoleProprietorBusinessDetailsStep.addressInvalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters - . ' / & # @ % `,
  'schema.SoleProprietorBusinessDetailsStep.invalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters . , _ ' + - / ! ? % ( )[ ] `,
  'schema.SoleProprietorBusinessDetailsStep.invalidWhiteSpaces': `(!) Please remove the leading and trialing white spaces.`,
  'schema.SoleProprietorBusinessDetailsStep.invalidNewLine': `(!) Please remove new line`,
  'schema.SoleProprietorBusinessDetailsStep.businessCity': `(!) City is required`,
  'schema.SoleProprietorBusinessDetailsStep.validBusinessCity': `(!) Please provide a valid city name`,
  'schema.SoleProprietorBusinessDetailsStep.businessState': `(!) State is required`,
  'schema.SoleProprietorBusinessDetailsStep.businessZipCodeMatch': `(!) Please enter a valid ZIP Code`,
  'schema.SoleProprietorBusinessDetailsStep.businessZipCodeReq': `(!) ZIP Code is required`,
  'schema.SoleProprietorBusinessDetailsStep.businessPhoneMatch': `(!) Please enter a valid phone number`,
  'schema.SoleProprietorBusinessDetailsStep.businessPhoneReq': `(!) Phone number is required`,
  'schema.SoleProprietorBusinessDetailsStep.industryType': `(!) Please select an industry type`,
  'schema.SoleProprietorBusinessDetailsStep.industryCategory': `(!) Please select an industry category`,
  'schema.SoleProprietorBusinessDetailsStep.businessIdentification': `(!) Please select an identification`,
  'schema.SoleProprietorBusinessDetailsStep.controllerSsn9': `(!) Please provide a valid SSN`,
  'schema.SoleProprietorBusinessDetailsStep.controllerSsn9Req': `(!) SSN is required`,
  // END -  STEPS - SoleProprietorBusinessDetailsStep -- schema

  // START -  STEPS - BusinessOwnersStep
  'steps.BusinessOwnersStep.modalTitle': `Enter business owner details`,
  'steps.BusinessOwnersStep.title': `Enter business owner details`,
  'steps.BusinessOwnersStep.radioLabel': `Do you, the controller, own 25% or more of the business?`,
  'steps.BusinessOwnersStep.radioDesc': `You are at at the maximum of four owners. Please remove an owner if you want to add the controller as an owner.`,
  'steps.BusinessOwnersStep.radioYes': `Yes`,
  'steps.BusinessOwnersStep.radioNo': `No`,
  'steps.BusinessOwnersStep.title1': `Business Owners`,
  'steps.BusinessOwnersStep.personInfoCardDesc': `Controller, Owner`,
  'steps.BusinessOwnersStep.disabledText': `View/edit details in Controller step`,
  'steps.BusinessOwnersStep.personInfoCardDesc1': `Owner`,
  'steps.BusinessOwnersStep.personInfoCard': `This owner is missing some information. Please update it to proceed.`,
  'steps.BusinessOwnersStep.Button': `Click to add a business owner`,
  'steps.BusinessOwnersStep.title2': `Removed Business Owners`,
  'steps.BusinessOwnersStep.text': `These owners are ones we already have data for, but you have marked for removal. You may restore them to keep them.`,
  'steps.BusinessOwnersStep.text1': `You already have the max number of business owners. Remove one if you want to restore a removed business owner.`,
  'steps.BusinessOwnersStep.personInfoCardDesc2': `Owner`,
  'steps.BusinessOwnersStep.personInfoCardAction': `Restore this business owner`,
  'steps.BusinessOwnersStep.soleOwnerCheckboxLabelBeforeName': `Check this box to verify that `,
  'steps.BusinessOwnersStep.soleOwnerCheckboxLabelAfterName': ` is the sole owner of your business`,
  // END -  STEPS - BusinessOwnersStep

  // START -  schema - BusinessOwnersStep -- schema
  'schema.businessOwnerFormSchema.firstName': `(!) First name is required`,
  'schema.businessOwnerFormSchema.lastName': `(!) Last name is required`,
  'schema.businessOwnerFormSchema.email': `(!) Email is required`,
  'schema.businessOwnerFormSchema.jobTitle': `(!) Job Title is required`,
  'schema.businessOwnerFormSchema.addressLine1': `(!) Address Line 1 is required`,
  'schema.businessOwnerFormSchema.city': `(!) City is required`,
  'schema.businessOwnerFormSchema.addressInvalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters - . ' / & # @ % `,
  'schema.businessOwnerFormSchema.invalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters . , _ ' + - / ! ? % ( )[ ] `,
  'schema.businessOwnerFormSchema.invalidWhiteSpaces': `(!) Please remove the leading and trialing white spaces.`,
  'schema.businessOwnerFormSchema.validBusinessCity': `(!) Please provide a valid city name`,
  'schema.businessOwnerFormSchema.state': `(!) State is required`,
  'schema.businessOwnerFormSchema.zipCodeMatch': `(!) Please enter a valid ZIP code`,
  'schema.businessOwnerFormSchema.zipCodeReq': `(!) ZIP code is required`,
  'schema.businessOwnerFormSchema.phoneMatch': `(!) Please enter a valid phone number`,
  'schema.businessOwnerFormSchema.isPhoneUSValid': `(!) Please enter a valid US phone number`,
  'schema.businessOwnerFormSchema.phoneReq': `(!) Phone number is required`,
  'schema.businessOwnerFormSchema.birthDateReq': `(!) Birth date is required`,
  'schema.businessOwnerFormSchema.birthDateTest': `(!) The business owner must be at least 18 years old`,
  'schema.businessOwnerFormSchema.ssn9Math': `(!) Please provide a valid SSN`,
  'schema.businessOwnerFormSchema.ssn9Req': `(!) SSN is required`,
  'schema.businessOwnerFormSchema.maxStringLengthAlert': `(!) Should be less than {word} characters`,
  'schema.businessOwnerFormSchema.soleOwnerCheckboxRequired': `(!) Please verify the above`,
  // END -  schema - BusinessOwnersStep -- schema

  // START -  schema - businessOwnersStepSchema -- schema
  'schema.businessOwnersStepSchema.controllerIsOwner': `(!) First name is required`,
  'schema.businessOwnersStepSchema.ownersValid': `(!) Last name is required`,
  // END -  schema - businessOwnersStepSchema -- schema

  // START - BusinessOwnerForm
  'steps.BusinessOwnerForm.labelFN': `First Name`,
  'steps.BusinessOwnerForm.labelMN': `Middle Name`,
  'steps.BusinessOwnerForm.labelLN': `Last Name`,
  'steps.BusinessOwnerForm.selectLabel': `Job Title`,
  'steps.BusinessOwnerForm.selectPlc': `Select a job title`,
  'steps.BusinessOwnerForm.inputLabel': `Job Title Description`,
  'steps.BusinessOwnerForm.inputPlaceholderJobTitleIsOther': `Please provide a description of your job title`,
  'steps.BusinessOwnerForm.inputPlaceholderJobTitleIsOtherNot': `Job description not required`,
  'steps.BusinessOwnerForm.email': `Email`,
  'steps.BusinessOwnerForm.labelAddr': `Address`,
  'steps.BusinessOwnerForm.labelPlc': `Address Line 1`,
  'steps.BusinessOwnerForm.labelAddr2': `Address Line 2`,
  'steps.BusinessOwnerForm.labelAddr3': `Address Line 3`,
  'steps.BusinessOwnerForm.labelCity': `City`,
  'steps.BusinessOwnerForm.placeCity': `City`,
  'steps.BusinessOwnerForm.labelZip': `ZIP Code`,
  'steps.BusinessOwnerForm.placeZip': `ZIP Code`,
  'steps.BusinessOwnerForm.text': `By federal law, we are required to verify the business owner's identity using the Social Security Number. We will need your full SSN to verify you.`,
  'steps.BusinessOwnerForm.btnChancel': `Cancel`,
  'steps.BusinessOwnerForm.btnRmv': `Remove`,
  'steps.BusinessOwnerForm.btnSave': `Save`,
  'steps.BusinessOwnerForm.btnAdd': `Add`,
  // END - BusinessOwnerForm

  // START - ControllerDetailsStep
  'steps.ControllerDetailsStep.title': `Tell us about yourself`,
  'steps.ControllerDetailsStep.alertMsg': `The controller oversees the business and financial operations and shares responsibility for the organization's economic and financial performance.`,
  'steps.ControllerDetailsStep.text': `Please provide your personal information. We will verify that you are a controller of the business.`,
  'steps.ControllerDetailsStep.inputFN': `First Name`,
  'steps.ControllerDetailsStep.inputMN': `Middle Name`,
  'steps.ControllerDetailsStep.inputLN': `Last Name`,
  'steps.ControllerDetailsStep.email': `Email`,
  'steps.ControllerDetailsStep.selectLabel': `Job Title`,
  'steps.ControllerDetailsStep.selectPlc': `Select a job title`,
  'steps.ControllerDetailsStep.inputLabel': `Job Title Description`,
  'steps.ControllerDetailsStep.inputPlaceholderJobTitleIsOther': `Please provide a description of your job title`,
  'steps.ControllerDetailsStep.inputPlaceholderJobTitleIsOtherNot': `Job description not required`,
  'steps.ControllerDetailsStep.inputText': `Job description not required`,
  'steps.ControllerDetailsStep.ssnHelperText': `By federal law, we are required to verify the business controller's identity using the Social Security Number. We will need your full SSN to verify you.`,
  'steps.ControllerDetailsStep.controllerAddressSectionTitle': `What is your personal address?`,
  'steps.ControllerDetailsStep.labelAddr': `Address`,
  'steps.ControllerDetailsStep.labelPlc': `Address Line 1`,
  'steps.ControllerDetailsStep.plcAddr2': `Address Line 2`,
  'steps.ControllerDetailsStep.plcAddr3': `Address Line 3`,
  'steps.ControllerDetailsStep.labelCity': `City`,
  'steps.ControllerDetailsStep.placeCity': `City`,
  'steps.ControllerDetailsStep.labelZip': `ZIP Code`,
  'steps.ControllerDetailsStep.placeZip': `ZIP Code`,
  // END - ControllerDetailsStep

  // START SCHEMA -- controllerDetailsSchema
  'schema.controllerDetailsSchema.controllerFirstName': `(!) First name is required`,
  'schema.controllerDetailsSchema.controllerLastName': `(!) Last name is required`,
  'schema.controllerDetailsSchema.controllerEmail': `(!) Email is required`,
  'schema.controllerDetailsSchema.controllerJobTitle': `(!) Please select a job title`,
  'schema.controllerDetailsSchema.controllerJobTitleDescription': `(!) Please provide a description for your job title.`,
  'schema.controllerDetailsSchema.invalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters . , _ ' + - / ! ? % ( )[ ] `,
  'schema.controllerDetailsSchema.invalidWhiteSpaces': `(!) Please remove the leading and trialing white spaces.`,
  'schema.controllerDetailsSchema.controllerSsn9Match': `(!) Please provide a valid SSN`,
  'schema.controllerDetailsSchema.controllerSsn9Req': `(!) SSN is required`,
  'schema.controllerDetailsSchema.controllerAddressLine1': `(!) Address Line 1 is required`,
  'schema.controllerDetailsSchema.addressInvalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters - . ' / & # @ % `,
  'schema.controllerDetailsSchema.maxStringLengthAlert': `(!) Should be less than {word} characters`,
  'schema.controllerDetailsSchema.controllerCity': `(!) City is required`,
  'schema.controllerDetailsSchema.validBusinessCity': `(!) Please provide a valid city name`,
  'schema.controllerDetailsSchema.controllerState': `(!) State is required`,
  'schema.controllerDetailsSchema.controllerZipCodeMatch': `(!) Please enter a valid ZIP code`,
  'schema.controllerDetailsSchema.controllerZipReq': `(!) Zip code is required`,
  'schema.controllerDetailsSchema.controllerPhoneMatch': `(!) Please enter a valid phone number`,
  'schema.controllerDetailsSchema.isPhoneUSValid': `(!) Please enter a valid US phone number`,
  'schema.controllerDetailsSchema.controllerPhoneReq': `(!) Phone number is required`,
  'schema.controllerDetailsSchema.controllerBirthDateReq': `(!) Birth date is required`,
  'schema.controllerDetailsSchema.controllerBirthDateTest': `(!) The controller must be at least 18 years old`,
  // END SCHEMA -- controllerDetailsSchema

  // START - DecisionMakersStep
  'steps.DecisionMakersStep.modalTitle': `Enter decision maker details`,
  'steps.DecisionMakersStep.title': `Additional Decision Makers`,
  'steps.DecisionMakersStep.radioLabel': `Are there any general partners or managing members within in your business who can make decisions on behalf of your company that we have not already captured in the business details?`,
  'steps.DecisionMakersStep.radioYes': `Yes`,
  'steps.DecisionMakersStep.radioNo': `No`,
  'steps.DecisionMakersStep.title1': `Listed business decision makers`,
  'steps.DecisionMakersStep.personInfoCardDesc': `Controller, Owner`,
  'steps.DecisionMakersStep.personInfoCardDisText': `View/edit details in controller step`,
  'steps.DecisionMakersStep.personInfoCardDesc1': `Owner`,
  'steps.DecisionMakersStep.personInfoCardDisText1': `View/edit details in owners step`,
  'steps.DecisionMakersStep.personInfoCardDesc2': `Decision Maker`,
  'steps.DecisionMakersStep.personInfoCardDisText2': `This decision maker is missing some information. Please update it to proceed.`,
  'steps.DecisionMakersStep.button': `Click to add a decision maker`,
  'steps.DecisionMakersStep.title2': `Removed Decision Makers`,
  'steps.DecisionMakersStep.text': `These decision makers are ones we already have data for, but you have marked for removal. You may restore them to keep them.`,
  'steps.DecisionMakersStep.personInfoCardDesc3': `Owner`,
  'steps.DecisionMakersStep.personInfoCardActionText': `Restore this decision maker`,
  // END - DecisionMakersStep

  // START SCHEMA -- createDecisionMakerFormSchema
  'schema.createDecisionMakerFormSchema.firstName': `(!) First name is required`,
  'schema.createDecisionMakerFormSchema.lastName': `(!) Last name is required`,
  'schema.createDecisionMakerFormSchema.jobTitle': `(!) Please select a job title`,
  'schema.createDecisionMakerFormSchema.jobTitleDescription': `(!) Please provide a description for your job title.`,
  'schema.createDecisionMakerFormSchema.email': `(!) Email is required`,
  'schema.createDecisionMakerFormSchema.invalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters . , _ ' + - / ! ? % ( )[ ] `,
  'schema.createDecisionMakerFormSchema.invalidWhiteSpaces': `(!) Please remove the leading and trialing white spaces.`,
  'schema.createDecisionMakerFormSchema.addressInvalidCharacters': `(!) Invalid characters. Please use only letters, numbers, and allowed characters - . ' / & # @ % `,
  'schema.createDecisionMakerFormSchema.addressLine1': `(!) Address is required`,
  'schema.createDecisionMakerFormSchema.maxStringLengthAlert': `(!) Should be less than {word} characters`,
  'schema.createDecisionMakerFormSchema.city': `(!) City is required`,
  'schema.createDecisionMakerFormSchema.validBusinessCity': `(!) Please provide a valid city name`,
  'schema.createDecisionMakerFormSchema.state': `(!) State is required`,
  'schema.createDecisionMakerFormSchema.zipCodeMatch': `(!) Please enter a valid ZIP code`,
  'schema.createDecisionMakerFormSchema.zipReq': `(!) Zip code is required`,
  'schema.createDecisionMakerFormSchema.phoneMatch': `(!) Please enter a valid phone number`,
  'schema.createDecisionMakerFormSchema.isPhoneUSValid': `(!) Please enter a valid US phone number`,
  'schema.createDecisionMakerFormSchema.phoneReq': `(!) Phone number is required`,
  'schema.createDecisionMakerFormSchema.birthDateReq': `(!) Birth date is required`,
  'schema.createDecisionMakerFormSchema.birthDateTest': `(!) The controller must be at least 18 years old`,
  // END SCHEMA -- createDecisionMakerFormSchema

  // START SCHEMA -- decisionMakersStepSchema
  'schema.decisionMakersStepSchema.decisionMakersExist': `(!) Please specify if there are any decision makers.`,
  'schema.decisionMakersStepSchema.decisionMakersValid': `(!) One or more decision makers are missing information. Please update them.`,
  'schema.decisionMakersStepSchema.maxStringLengthAlert': `(!) Should be less than {word} characters`,
  // END SCHEMA -- decisionMakersStepSchema

  // START - DecisionMakerForm
  'steps.DecisionMakerForm.inputFN': `First Name`,
  'steps.DecisionMakerForm.inputMN': `Middle Name`,
  'steps.DecisionMakerForm.inputLN': `Last Name`,
  'steps.DecisionMakerForm.selectLabel': `Job Title`,
  'steps.DecisionMakerForm.selectPlc': `Select a job title`,
  'steps.DecisionMakerForm.inputLabel': `Job Title Description`,
  'steps.DecisionMakerForm.inputPlaceholderJobTitleIsOther': `Please provide a description of your job title`,
  'steps.DecisionMakerForm.inputPlaceholderJobTitleIsOtherNot': `Job description not required`,
  'steps.DecisionMakerForm.inputText': `Email`,
  'steps.DecisionMakerForm.labelAddr': `Address`,
  'steps.DecisionMakerForm.plcAddr2': `Address Line 2`,
  'steps.DecisionMakerForm.plcAddr3': `Address Line 3`,
  'steps.DecisionMakerForm.labelCity': `City`,
  'steps.DecisionMakerForm.placeCity': `City`,
  'steps.DecisionMakerForm.labelZip': `ZIP Code`,
  'steps.DecisionMakerForm.placeZip': `ZIP Code`,
  'steps.DecisionMakerForm.btnCancel': `Cancel`,
  'steps.DecisionMakerForm.btnRemove': `Remove`,
  'steps.DecisionMakerForm.btnSave': `Save`,
  'steps.DecisionMakerForm.btnAdd': `Add`,
  // END - DecisionMakerForm

  // START - AdditionalDetailsStep
  'steps.AdditionalDetailsStep.title':
    'Based on what you told us so far, we need additional info',
  'steps.AdditionalDetailsStep.listSchemaError':
    '(!) Please choose at least one option',
  'steps.AdditionalDetailsStep.stringSchemaError':
    '(!) Please answer this question',
  // END - AdditionalDetailsStep

  // START - ReviewStep
  'steps.ReviewStep.title': 'Review',
  'steps.ReviewStep.alertTitle': 'Ensure all of the information is correct',
  'steps.ReviewStep.text': `After you submit this form, it takes time to review your information and complete onboarding. During this time, you will not be able to edit this data, so make sure everything is correct.`,
  'steps.ReviewStep.groupText': `Key:`,
  'steps.ReviewStep.groupMark': `Information you added`,
  'steps.ReviewStep.groupMark1': `Information you removed`,
  // END - ReviewStep

  // START - valuesMap
  'steps.valuesMap.statusBadgesADD': 'Added',
  'steps.valuesMap.statusBadgesREMOVE': 'Removed',
  'steps.valuesMap.statusBadgesUPDATE': 'Updated',
  'steps.valuesMap.statusBadgesUNCHANGED': 'Unchanged',
  // -----

  'steps.valuesMap.subtitleBuss': 'Business Owner',
  'steps.valuesMap.subtitleDec': 'Decision Maker',
  'steps.valuesMap.firstName': 'First Name',
  'steps.valuesMap.middleName': 'Middle Name',
  'steps.valuesMap.lastName': 'Last Name',
  'steps.valuesMap.jobTitle': 'Job Title',
  'steps.valuesMap.jobTitleDescription': 'Job Title Description',
  'steps.valuesMap.email': 'Email',
  'steps.valuesMap.addressLine1': 'Address Line 1',
  'steps.valuesMap.addressLine2': 'Address Line 2',
  'steps.valuesMap.addressLine3': 'Address Line 3',
  'steps.valuesMap.city': 'City',
  'steps.valuesMap.state': 'State',
  'steps.valuesMap.zipCode': 'ZIP Code',
  'steps.valuesMap.phone': 'Phone',
  'steps.valuesMap.birthDate': 'Birth Date',
  'steps.valuesMap.ssn9': 'Social Security Number',
  // -----
  'steps.valuesMap.title': 'Business Details',
  'steps.valuesMap.notAvailable': 'N/A',
  'steps.valuesMap.legalStructure': 'Legal Structure',
  'steps.valuesMap.businessName': 'Business Name',
  'steps.valuesMap.solePropBusinessName': 'Legal Name',
  'steps.valuesMap.businessAliasName': 'Business Alias',
  'steps.valuesMap.solePropBusinessAliasName': 'Doing business as name',
  'steps.valuesMap.businessEmail': 'Business Email',
  'steps.valuesMap.country': 'Country of Formation',
  'steps.valuesMap.yearOfFormation': 'Year of Formation',
  'steps.valuesMap.ein': 'EIN',
  'steps.valuesMap.businessIdentification': 'Business identifier',
  'steps.valuesMap.website': 'Website',
  'steps.valuesMap.businessDescription': 'Business Description',
  'steps.valuesMap.businessAddressLine1': 'Business Address Line 1',
  'steps.valuesMap.businessAddressLine2': 'Business Address Line 2',
  'steps.valuesMap.businessAddressLine3': 'Business Address Line 3',
  'steps.valuesMap.businessCity': 'City',
  'steps.valuesMap.businessState': 'State',
  'steps.valuesMap.businessZipCode': 'ZIP Code',
  'steps.valuesMap.businessPhone': 'Phone',
  'steps.valuesMap.industryCategory': 'Industry Category',
  'steps.valuesMap.industryType': 'Industry Type',
  // -----
  'steps.valuesMap.controllerIsOwner': 'Controller',
  'steps.valuesMap.controllerIsOwnerBuss': ', Business Owner',
  'steps.valuesMap.controllerFirstName': 'First Name',
  'steps.valuesMap.controllerMiddleName': 'Middle Name',
  'steps.valuesMap.controllerLastName': 'Last Name',
  'steps.valuesMap.controllerEmail': 'Email',
  'steps.valuesMap.controllerJobTitle': 'Job Title',
  'steps.valuesMap.controllerJobTitleDescription': 'Job Title Description',
  'steps.valuesMap.controllerAddressLine1': 'Controller Address Line 1',
  'steps.valuesMap.controllerAddressLine2': 'Controller Address Line 2',
  'steps.valuesMap.controllerAddressLine3': 'Controller Address Line 3',
  'steps.valuesMap.controllerCity': 'City',
  'steps.valuesMap.controllerState': 'State',
  'steps.valuesMap.controllerZipCode': 'ZIP Code',
  'steps.valuesMap.controllerPhone': 'Phone',
  'steps.valuesMap.controllerBirthDate': 'Birth Date',
  'steps.valuesMap.controllerSsn9': 'Social Security Number',
  // END - valuesMap

  // START - VerificationsStep
  'steps.VerificationsStep.title': `Terms and Conditions`,
  'steps.VerificationsStep.text': `Please read the Deposit Agreement and review the Online Disclosure for Caterease Banking by J.P. Morgan to complete the process.`,
  'steps.VerificationsStep.title1': `Deposit Account Agreement`,
  'steps.VerificationsStep.group': `Document has been reviewed`,
  'steps.VerificationsStep.groupX': `Document has not been reviewed`,
  'steps.VerificationsStep.title2': `Online Disclosure`,
  'steps.VerificationsStep.anchor': `Open in new tab: Online Disclosure`,
  'steps.VerificationsStep.badge': `Document has been opened`,
  'steps.VerificationsStep.badgeX': `Document has not been opened`,
  'steps.VerificationsStep.attestedDataCorrectI': `I, `,
  'steps.VerificationsStep.attestedDataCorrectDesc': `, hereby certify, to the best of my knowledge, that the information provided is complete and correct.`,
  'steps.VerificationsStep.attestationLabelBeforeName': `I certify this bank account will be used for business purposes and not for personal, family, or household use. I certify that `,
  'steps.VerificationsStep.attestationLabelAfterName': ` has authorized me to open and close bank accounts, make deposits and payments, and delegate these authorities.`,
  'steps.VerificationsStep.solePropAttestationLabel': `I certify this bank account will be used for business purposes and not personal, family, or household use.  I certify that, as the Sole Proprietor, I am authorized to open and close accounts, make deposits and payments, and delegate these authorities.`,
  'steps.VerificationsStep.attestedReadDocuments': `I have read and agree to the E-Sign Disclosure and Consent, the Deposit Account Agreement, and the certifications directly above.`,
  // END - VerificationsStep

  // START - PdfDisplay
  'steps.PdfDisplay.Document': `Loading PDF...`,
  // END - PdfDisplay

  // START - PdfDisplay
  'schema.verificationsStepSchema.reviewedTerms': `(!) Please review this document`,
  'schema.verificationsStepSchema.reviewedDisclosure': `(!) Please review this document`,
  'schema.verificationsStepSchema.attestedDataCorrect': `(!) You must certify the above.`,
  'schema.verificationsStepSchema.attestedAuthorized': `(!) You must certify the above.`,
  'schema.verificationsStepSchema.attestedReadDocuments': `(!) Please review the documents above.`,
  'schema.verificationsStepSchema.attestedReadDocumentsTerms': `(!) Please review the documents above.`,
  'schema.verificationsStepSchema.attestedReadDocumentsDisc': `(!) You must certify the above.`,
  // END - PdfDisplay
};

export { contentTokensOnboardingEng };
