export const industryCategoriesMock: any = {
    metadata: {
      page: 0,
      limit: 25,
      total_items: 22,
    },
    items: [
      {
        industryCategory: 'UNASSIGNED',
        industryTypes: ['UNASSIGNED'],
      },
      {
        industryCategory: 'Agriculture, Forestry, Fishing and Hunting',
        industryTypes: [
          'Soybean Farming',
          'Oilseed (Except Soybean) Farming',
          'Dry Pea And Bean Farming',
          'Wheat Farming',
          'Corn Farming',
          'Rice Farming',
          'Oilseed And Grain Combination Farming',
          'All Other Grain Farming',
          'Potato Farming',
          'Other Vegetable (Except Potato) And Melon Farming',
          'Orange Groves',
          'Citrus (Except Orange) Groves',
          'Apple Orchards',
          'Grape Vineyards',
          'Strawberry Farming',
          'Berry (Except Strawberry) Farming',
          'Tree Nut Farming',
          'Fruit And Tree Nut Combination Farming',
          'Other Noncitrus Fruit Farming',
          'Mushroom Production',
          'Other Food Crops Grown Under Cover',
          'Nursery And Tree Production',
          'Floriculture Production',
          'Tobacco Farming',
          'Cotton Farming',
          'Sugarcane Farming',
          'Hay Farming',
          'Sugar Beet Farming',
          'Peanut Farming',
          'All Other Miscellaneous Crop Farming',
          'Beef Cattle Ranching And Farming',
          'Cattle Feedlots',
          'Dairy Cattle And Milk Production',
          'Dual-Purpose Cattle Ranching And Farming',
          'Hog And Pig Farming',
          'Chicken Egg Production',
          'Broilers And Other Meat Type Chicken Production',
          'Turkey Production',
          'Poultry Hatcheries',
          'Other Poultry Production',
          'Sheep Farming',
          'Goat Farming',
          'Finfish Farming And Fish Hatcheries',
          'Shellfish Farming',
          'Other Aquaculture',
          'Apiculture',
          'Horses And Other Equine Production',
          'Fur-Bearing Animal And Rabbit Production',
          'All Other Animal Production',
          'Timber Tract Operations',
          'Forest Nurseries And Gathering Of Forest Products',
          'Logging',
          'Finfish Fishing',
          'Shellfish Fishing',
          'Other Marine Fishing',
          'Hunting And Trapping',
          'Cotton Ginning',
          'Soil Preparation Planting And Cultivating',
          'Crop Harvesting Primarily By Machine',
          'Postharvest Crop Activities (Except Cotton Ginning)',
          'Farm Labor Contractors And Crew Leaders',
          'Farm Management Services',
          'Support Activities For Animal Production',
          'Support Activities For Forestry',
        ],
      },
      {
        industryCategory: 'Mining, Quarrying, and Oil and Gas Extraction',
        industryTypes: [
          'Crude Petroleum Extraction',
          'Iron Ore Mining',
          'Dimension Stone Mining And Quarrying',
          'Crushed And Broken Limestone Mining And Quarrying',
          'Crushed And Broken Granite Mining And Quarrying',
          'Other Crushed And Broken Stone Mining And Quarrying',
          'Construction Sand And Gravel Mining',
          'Industrial Sand Mining',
          'Drilling Oil And Gas Wells',
          'Support Activities For Oil And Gas Operations',
          'Support Activities For Coal Mining',
          'Support Activities For Metal Mining',
          'Support Activities For Non-Metallic Minerals (Except Fuels)',
          'Kaolin, Clay, and Ceramic and Refractory Minerals Mining',
          'Other Nonmetallic Mineral Mining and Quarrying',
          'Underground Coal Mining',
          'Natural Gas Extraction',
          'Copper, Nickel, Lead, and Zinc Mining',
          'Oilfield Service',
          'Engineering Contractors',
          'Natural Gas Extraction And Liquification',
          'Integrated Oil and Gas',
          'Diversified Mining',
          'Diamond And Precious Stone Mining',
          'Surface Coal Mining',
          'Other Metal Ore Mining',
          'Gold Ore and Silver Ore Mining',
        ],
      },
      {
        industryCategory: 'Utilities',
        industryTypes: [
          'Hydroelectric Power Generation',
          'Fossil Fuel Electric Power Generation',
          'Nuclear Electric Power Generation',
          'Solar Electric Power Generation',
          'Wind Electric Power Generation',
          'Geothermal Electric Power Generation',
          'Biomass Electric Power Generation',
          'Other Electric Power Generation',
          'Electric Bulk Power Transmission And Control',
          'Electric Power Distribution',
          'Natural Gas Distribution',
          'Water Supply And Irrigation Systems',
          'Sewage Treatment Facilities',
          'Steam And Air-Conditioning Supply',
          'Integrated Utility',
          'Merchant Energy',
        ],
      },
      {
        industryCategory: 'Construction',
        industryTypes: [
          'Residential Remodelers',
          'Industrial Building Construction (Except Operative Builders)',
          'Comml & Instit Bldg Construction (Except Operative Builders)',
          'Water And Sewer Line And Related Structures Construction',
          'Oil And Gas Pipeline And Related Structures Construction',
          'Power & Communication Line & Related Structures Construction',
          'Land Subdivision',
          'Highway Street And Bridge Construction',
          'Other Heavy And Civil Engineering Construction',
          'Poured Concrete Foundation And Structure Contractors',
          'Structural Steel And Precast Concrete Contractors',
          'Framing Contractors',
          'Masonry Contractors',
          'Glass And Glazing Contractors',
          'Roofing Contractors',
          'Siding Contractors',
          'Other Foundation Structure and Building Exterior Contract',
          'Plumbing Heating And Air-Conditioning Contractors',
          'Other Building Equipment Contractors',
          'Painting And Wall Covering Contractors',
          'Flooring Contractors',
          'Tile And Terrazzo Contractors',
          'Finish Carpentry Contractors',
          'Other Building Finishing Contractors',
          'Site Preparation Contractors',
          'All Other Specialty Trade Contractors',
          'Drywall and Insulation Contractors',
          'Residential Building Construction (Exc Operative Builders)',
          'New Housing Operative Builders (Single Family And Condo)',
          'Apartment Construction Operative Builders (Apartment)',
          'Industrial/Warehouse Operative Builders (Industrial)',
          'Office Operative Builders (Office Buildings)',
          'Retail Operative Builders (Retail Buildings)',
          'Hotel Operative Builders (Hotels)',
          'Residential Land Subdividing (Sale To Home Builders)',
          'Commercial Land Subdividing (Sale To Commercial Builders)',
          'New Single-Family Housing Construct (ex For-Sale Builders)',
          'New Housing For-Sale Builders',
          'Electrical Contractors and Other Wiring Installation Contractors',
          'New Multifamily Housing Construct (ex For-Sale Builders)',
        ],
      },
      {
        industryCategory: 'Manufacturing',
        industryTypes: [
          'Dog And Cat Food Manufacturing',
          'Other Animal Food Manufacturing',
          'Flour Milling',
          'Rice Milling',
          'Malt Manufacturing',
          'Soybean and Other Oilseed Processing',
          'Fats And Oils Refining And Blending',
          'Breakfast Cereal Manufacturing',
          'Beet Sugar Manufacturing',
          'Cane Sugar Manufacturing',
          'Non-Chocolate Confectionery Manufacturing',
          'Chocolate and Confectionery Manufacturing from Cacao Beans',
          'Confectionery Manufacturing from Purchased Chocolate',
          'Frozen Fruit Juice And Vegetable Manufacturing',
          'Frozen Specialty Food Manufacturing',
          'Fruit And Vegetable Canning',
          'Specialty Canning',
          'Dried And Dehydrated Food Manufacturing',
          'Fluid Milk Manufacturing',
          'Creamery Butter Manufacturing',
          'Cheese Manufacturing',
          'Dry Condensed And Evaporated Dairy Product Manufacturing',
          'Ice Cream And Frozen Dessert Manufacturing',
          'Animal (Except Poultry) Slaughtering',
          'Meat Processed From Carcasses',
          'Rendering And Meat By-Product Processing',
          'Poultry Processing',
          'Seafood Product Preparation And Packaging',
          'Retail Bakeries',
          'Commercial Bakeries',
          'Cookie And Cracker Manufacturing',
          'Dry Pasta Dough and Flour Mixes Manuf from Purchased Flour',
          'Tortilla Manufacturing',
          'Roasted Nuts And Peanut Butter Manufacturing',
          'Other Snack Food Manufacturing',
          'Coffee And Tea Manufacturing',
          'Flavoring Syrup And Concentrate Manufacturing',
          'Mayonnaise Dressing And Other Prepared Sauce Manufacturing',
          'Spice And Extract Manufacturing',
          'Perishable Prepared Food Manufacturing',
          'All Other Miscellaneous Food Manufacturing',
          'Soft Drink Manufacturing',
          'Bottled Water Manufacturing',
          'Ice Manufacturing',
          'Breweries',
          'Wineries',
          'Distilleries',
          'Tobacco Manufacturing',
          'Fiber Yarn And Thread Mills',
          'Broadwoven Fabric Mills',
          'Narrow Fabric Mills And Schiffli Machine Embroidery',
          'Nonwoven Fabric Mills',
          'Knit Fabric Mills',
          'Textile And Fabric Finishing Mills',
          'Fabric Coating Mills',
          'Carpet And Rug Mills',
          'Curtain And Linen Mills',
          'Textile Bag And Canvas Mills',
          'Rope Cordage Twine Tire Cord and Tire Fabric Mills',
          'All Other Miscellaneous Textile Product Mills',
          'Cut And Sew Apparel Contractors',
          'Apparel Accessories And Other Apparel Manufacturing',
          'Leather And Hide Tanning And Finishing',
          'Footwear Manufacturing',
          'Sawmills',
          'Wood Preservation',
          'Hardwood Veneer And Plywood Manufacturing',
          'Softwood Veneer And Plywood Manufacturing',
          'Reconstituted Wood Product Manufacturing',
          'Wood Window And Door Manufacturing',
          'Cut Stock Resawing Lumber And Planing',
          'Other Millwork (Including Flooring )',
          'Wood Container And Pallet Manufacturing',
          'Manufactured Home (Mobile Home) Manufacturing',
          'Prefabricated Wood Building Manufacturing',
          'Pulp Mills',
          'Paperboard Mills',
          'Corrugated And Solid Fiber Box Manufacturing',
          'Folding Paperboard Box Manufacturing',
          'Other Paperboard Container Manufacturing',
          'Paper Bag And Coated And Treated Paper Manufacturing',
          'Stationery Product Manufacturing',
          'Sanitary Paper Product Manufacturing',
          'All Other Converted Paper Product Manufacturing',
          'Commercial Screen Printing',
          'Book Printing',
          'Support Activities For Printing',
          'Petroleum Refineries',
          'Asphalt Paving Mixture And Block Manufacturing',
          'Asphalt Shingle And Coating Materials Manufacturing',
          'Petroleum Lubricating Oil And Grease Manufacturing',
          'All Other Petroleum And Coal Products Manufacturing',
          'Petrochemical Manufacturing',
          'Industrial Gas Manufacturing',
          'Synthetic Dye And Pigment Manufacturing',
          'Other Basic Inorganic Chemical Manufacturing',
          'Ethyl Alcohol Manufacturing',
          'Cyclic Crude, Intermediate, and Gum and Wood Chemical Manufacturing',
          'All Other Basic Organic Chemical Manufacturing',
          'Plastics Material And Resin Manufacturing',
          'Synthetic Rubber Manufacturing',
          'Artificial And Synthetic Fibers And Filaments Manufacturing',
          'Nitrogenous Fertilizer Manufacturing',
          'Phosphatic Fertilizer Manufacturing',
          'Fertilizer (Mixing Only) Manufacturing',
          'Pesticide And Other Agricultural Chemical Manufacturing',
          'Medicinal And Botanical Manufacturing',
          'Pharmaceutical Preparation Manufacturing',
          'In-Vitro Diagnostic Substance Manufacturing',
          'Biological Product (Except Diagnostic) Manufacturing',
          'Paint And Coating Manufacturing',
          'Adhesive Manufacturing',
          'Soap And Other Detergent Manufacturing',
          'Polish And Other Sanitation Good Manufacturing',
          'Surface Active Agent Manufacturing',
          'Toilet Preparation Manufacturing',
          'Printing Ink Manufacturing',
          'Explosives Manufacturing',
          'Custom Compounding Of Purchased Resin',
          'All Other Miscellaneous Chemical Product Manufacturing',
          'Plastics Bag and Pouch Manufacturing',
          'Plastics Packaging Film & Sheet (Inc Laminated) Manufacturing',
          'Unlaminated Plastics Film and Sheet (except Packaging) Manufacturing',
          'Unlaminated Plastics Profile Shape Manufacturing',
          'Plastics Pipe And Pipe Fitting Manufacturing',
          'Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing',
          'Polystyrene Foam Product Manufacturing',
          'Urethane and Other Foam Product (except Polystyrene) Manufacturing',
          'Plastics Bottle Manufacturing',
          'Plastics Plumbing Fixture Manufacturing',
          'Tire Manufacturing (Except Retreading)',
          'Tire Retreading',
          'Rubber And Plastics Hoses And Belting Manufacturing',
          'Rubber Product Manufacturing For Mechanical Use',
          'All Other Rubber Product Manufacturing',
          'Pottery Ceramics And Plumbing Fixture Manufacturing',
          'Clay Building Material And Refractories Manufacturing',
          'Flat Glass Manufacturing',
          'Other Pressed And Blown Glass And Glassware Manufacturing',
          'Glass Container Manufacturing',
          'Glass Product Manufacturing Made Of Purchased Glass',
          'Cement Manufacturing',
          'Ready-Mix Concrete Manufacturing',
          'Concrete Block And Brick Manufacturing',
          'Concrete Pipe Manufacturing',
          'Other Concrete Product Manufacturing',
          'Lime Manufacturing',
          'Gypsum And Gypsum Product Manufacturing',
          'Abrasive Product Manufacturing',
          'Cut Stone And Stone Product Manufacturing',
          'Ground Or Treated Mineral And Earth Manufacturing',
          'Mineral Wool Manufacturing',
          'All Other Miscellaneous Nonmetallic Mineral Product Manufacturing',
          'Iron And Steel Mills And Ferroalloy Manufacturing',
          'Iron and Steel Pipe and Tube Manufacturing from Purchased Steel',
          'Steel Wire Drawing',
          'Alumina Refining and Primary Aluminum Production',
          'Secondary Smelting And Alloying Of Aluminum',
          'Aluminum Sheet Plate And Foil Manufacturing',
          'Other Aluminum Rolling Drawing and Extruding',
          'Nonferrous Metal (Except Aluminum) Smelting And Refining',
          'Copper Rolling Drawing Extruding And Alloying',
          'Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding',
          'Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except Copper and Aluminum)',
          'Iron Foundries',
          'Steel Investment Foundries',
          'Steel Foundries (Except Investment)',
          'Nonferrous Metal Die-Casting Foundries',
          'Other Nonferrous Metal Foundries (except Die-Casting)',
          'Iron And Steel Forging',
          'Nonferrous Forging',
          'Custom Roll Forming',
          'Powder Metallurgy Part Manufacturing',
          'Metal Crown Closure and Other Metal Stamping (ex Automotive)',
          'Metal Kitchen Cookware, Utensil, Cutlery, and Flatware (except Precious) Manufacturing',
          'Saw Blade and Handtool Manufacturing',
          'Prefabricated Metal Building And Component Manufacturing',
          'Fabricated Structural Metal Manufacturing',
          'Plate Work Manufacturing',
          'Metal Window And Door Manufacturing',
          'Sheet Metal Work Manufacturing',
          'Ornamental And Architectural Metal Work Manufacturing',
          'Power Boiler And Heat Exchanger Manufacturing',
          'Metal Tank (Heavy Gauge) Manufacturing',
          'Metal Can Manufacturing',
          'Other Metal Container Manufacturing',
          'Hardware Manufacturing',
          'Spring Manufacturing',
          'Other Fabricated Wire Product Manufacturing',
          'Machine Shops',
          'Precision Turned Product Manufacturing',
          'Bolt Nut Screw Rivet And Washer Manufacturing',
          'Metal Heat Treating',
          'Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers',
          'Electroplating Plating Polishing Anodizing And Coloring',
          'Industrial Valve Manufacturing',
          'Fluid Power Valve And Hose Fitting Manufacturing',
          'Plumbing Fixture Fitting And Trim Manufacturing',
          'Other Metal Valve And Pipe Fitting Manufacturing',
          'Ball And Roller Bearing Manufacturing',
          'Small Arms Ammunition Manufacturing',
          'Ammunition (Except Small Arms) Manufacturing',
          'Fabricated Pipe And Pipe Fitting Manufacturing',
          'All Other Miscellaneous Fabricated Metal Product Manufact',
          'Farm Machinery And Equipment Manufacturing',
          'Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing',
          'Construction Machinery Manufacturing',
          'Mining Machinery And Equipment Manufacturing',
          'Oil And Gas Field Machinery And Equipment Manufacturing',
          'Food Product Machinery Manufacturing',
          'Semiconductor Machinery Manufacturing',
          'Sawmill Woodworking and Paper Machinery Manufacturing',
          'Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing',
          'Heating Equipment (except Warm Air Furnaces) Manufacturing',
          'Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing',
          'Industrial Mold Manufacturing',
          'Special Die And Tool Die Set Jig And Fixture Manufacturing',
          'Cutting Tool And Machine Tool Accessory Manufacturing',
          'Machine Tool Manufacturing',
          'Rolling Mill and Other Metalworking Machinery Manufacturing',
          'Turbine And Turbine Generator Set Unit Manufacturing',
          'Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing',
          'Mechanical Power Transmission Equipment Manufacturing',
          'Other Engine Equipment Manufacturing',
          'Air And Gas Compressor Manufacturing',
          'Elevator And Moving Stairway Manufacturing',
          'Conveyor And Conveying Equipment Manufacturing',
          'Overhead Traveling Crane, Hoist, and Monorail System Manufacturing',
          'Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing',
          'Power-Driven Hand Tool Manufacturing',
          'Welding And Soldering Equipment Manufacturing',
          'Packaging Machinery Manufacturing',
          'Industrial Process Furnace And Oven Manufacturing',
          'Fluid Power Cylinder And Actuator Manufacturing',
          'Fluid Power Pump And Motor Manufacturing',
          'Electronic Computer Manufacturing',
          'Computer Storage Device Manufacturing',
          'Computer Terminal and Other Computer Peripheral Equipment Manufacturing',
          'Telephone Apparatus Manufacturing',
          'Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing',
          'Other Communications Equipment Manufacturing',
          'Audio And Video Equipment Manufacturing',
          'Semiconductor And Related Device Manufacturing',
          'Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing',
          'Electronic Connector Manufacturing',
          'Printed Circuit Assembly (Electronic Assembly) Manufacturing',
          'Electromedical And Electrotherapeutic Apparatus Manufacturin',
          'Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing',
          'Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use',
          'Totalizing Fluid Meter And Counting Device Manufacturing',
          'Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals',
          'Analytical Laboratory Instrument Manufacturing',
          'Irradiation Apparatus Manufacturing',
          'Residential Electric Lighting Fixture Manufacturing',
          'Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing',
          'Small Electrical Appliance Manufacturing',
          'Power Distribution And Specialty Transformer Manufacturing',
          'Motor And Generator Manufacturing',
          'Switchgear And Switchboard Apparatus Manufacturing',
          'Relay And Industrial Control Manufacturing',
          'Fiber Optic Cable Manufacturing',
          'Other Communication And Energy Wire Manufacturing',
          'Current-Carrying Wiring Device Manufacturing',
          'Noncurrent-Carrying Wiring Device Manufacturing',
          'Carbon And Graphite Product Manufacturing',
          'All Other Miscellaneous Electrical Equipment and Component Manufacturing',
          'Heavy Duty Truck Manufacturing',
          'Motor Vehicle Body Manufacturing',
          'Truck Trailer Manufacturing',
          'Motor Home Manufacturing',
          'Travel Trailer And Camper Manufacturing',
          'Motor Vehicle Gasoline Engine And Engine Parts Manufacturing',
          'Motor Vehicle Electrical and Electronic Equipment Manufacturing',
          'Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing',
          'Motor Vehicle Brake System Manufacturing',
          'Motor Vehicle Transmission and Power Train Parts Manufacturing',
          'Motor Vehicle Metal Stamping',
          'Other Motor Vehicle Parts Manufacturing',
          'Aircraft Manufacturing',
          'Aircraft Engine And Engine Parts Manufacturing',
          'Other Aircraft Part And Auxiliary Equipment Manufacturing',
          'Guided Missile And Space Vehicle Manufacturing',
          'Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing',
          'Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment Manufacturing',
          'Railroad Rolling Stock Manufacturing',
          'Ship Building And Repairing',
          'Boat Building',
          'Motorcycle Bicycle And Parts Manufacturing',
          'Military Armored Vehicle, Tank, and Tank Component Manufacturing',
          'All Other Transportation Equipment Manufacturing',
          'Wood Kitchen Cabinet And Counter Top Manufacturing',
          'Upholstered Household Furniture Manufacturing',
          'Nonupholstered Wood Household Furniture Manufacturing',
          'Institutional Furniture Manufacturing',
          'Wood Office Furniture Manufacturing',
          'Custom Architectural Woodwork And Millwork Manufacturing',
          'Showcase Partition Shelving And Locker Manufacturing',
          'Mattress Manufacturing',
          'Blind And Shade Manufacturing',
          'Surgical And Medical Instrument Manufacturing',
          'Surgical Appliance And Supplies Manufacturing',
          'Dental Equipment And Supplies Manufacturing',
          'Ophthalmic Goods Manufacturing',
          'Dental Laboratories',
          'Jewelry And Silverware Manufacturing',
          'Sporting And Athletic Goods Manufacturing',
          'Doll Toy And Game Manufacturing',
          'Office Supplies (Except Paper) Manufacturing',
          'Sign Manufacturing',
          'Gasket Packing And Sealing Device Manufacturing',
          'Musical Instrument Manufacturing',
          'Fastener Button Needle And Pin Manufacturing',
          'Broom Brush And Mop Manufacturing',
          'Burial Casket Manufacturing',
          'All Other Miscellaneous Manufacturing',
          'Cut and Sew Apparel Manufacturing (except Contractors)',
          'Paper Mills',
          'Other Measuring and Controlling Device Manufacturing',
          'Wet Corn Milling and Starch Manufacturing',
          'Photographic Film, Paper, Plate, Chemical, and Copy Toner Manufacturing',
          'Measuring, Dispensing, and Other Pumping Equipment Manufacturing',
          'Major Household Appliance Manufacturing',
          'Electric Lamp Bulb and Other Lighting Equipment Manufacturing',
          'Office Furniture (except Wood) Manufacturing',
          'All Other Industrial Machinery Manufacturing',
          'Commercial and Service Industry Machinery Manufacturing',
          'Motor Vehicle Seating and Interior Trim Manufacturing',
          'Household Furniture (except Wood and Upholstered) Manufacturing',
          'Apparel Knitting Mills',
          'Battery Manufacturing',
          'Small Arms Ordnance and Ordnance Accessories Manufacturing',
          'Automobile and Light Duty Motor Vehicle Manufacturing',
          'Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables',
          'Other Leather and Allied Product Manufacturing',
          'All Other Miscellaneous General Purpose Machinery Manufacturing',
          'All Other Plastics Product Manufacturing',
          'Other Electronic Component Manufacturing',
          'Engineered Wood Member Manufacturing',
          'All Other Miscellaneous Wood Product Manufacturing',
          'Frozen Cakes, Pies, and Other Pastries Manufacturing',
          'Manufacturing and Reproducing Magnetic and Optical Media',
          'Rolled Steel Shape Manufacturing',
          'Aluminum Foundries (except Die-Casting)',
          'Compost Manufacturing',
          'Bare Printed Circuit Board Manufacturing',
          'Commercial Printing (except Screen and Books)',
        ],
      },
      {
        industryCategory: 'Wholesale Trade',
        industryTypes: [
          'Automobile And Other Motor Vehicle Merchant Wholesalers',
          'Motor Vehicle Supplies And New Parts Merchant Wholesalers',
          'Tire And Tube Merchant Wholesalers',
          'Motor Vehicle Parts (Used) Merchant Wholesalers',
          'Furniture Merchant Wholesalers',
          'Home Furnishing Merchant Wholesalers',
          'Lumber Plywood Millwork & Wood Panel Merchant Wholesalers',
          'Brick, Stone, and Related Construction Material Merchant Wholesalers',
          'Roofing Siding And Insulation Material Merchant Wholesalers',
          'Other Construction Material Merchant Wholesalers',
          'Photographic Equipment And Supplies Merchant Wholesalers',
          'Office Equipment Merchant Wholesalers',
          'Computer and Computer Peripheral Equipment and Software Merchant Wholesalers',
          'Other Commercial Equipment Merchant Wholesalers',
          'Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers',
          'Ophthalmic Goods Merchant Wholesalers',
          'Other Professional Equipment and Supplies Merchant Wholesalers',
          'Metal Service Centers And Other Metal Merchant Wholesalers',
          'Coal And Other Mineral And Ore Merchant Wholesalers',
          'Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers',
          'Household Appliances, Electric Housewares, and Consumer Electronics Merchant Wholesalers',
          'Other Electronic Parts And Equipment Merchant Wholesalers',
          'Hardware Merchant Wholesalers',
          'Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers',
          'Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers',
          'Refrigeration Equipment And Supplies Merchant Wholesalers',
          'Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers',
          'Farm and Garden Machinery and Equipment Merchant Wholesalers',
          'Industrial Machinery And Equipment Merchant Wholesalers',
          'Industrial Supplies Merchant Wholesalers',
          'Service Establishment Equipment and Supplies Merchant Wholesalers',
          'Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers',
          'Sporting and Recreational Goods and Supplies Merchant Wholesalers',
          'Toy And Hobby Goods And Supplies Merchant Wholesalers',
          'Recyclable Material Merchant Wholesalers',
          'Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers',
          'Other Miscellaneous Durable Goods Merchant Wholesalers',
          'Printing And Writing Paper Merchant Wholesalers',
          'Stationary And Office Supplies Merchant Wholesalers',
          'Industrial And Personal Service Paper Merchant Wholesalers',
          "Drugs and Druggists' Sundries Merchant Wholesalers",
          'Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers',
          'Footwear Merchant Wholesalers',
          'General Line Grocery Merchant Wholesalers',
          'Packaged Frozen Food Merchant Wholesalers',
          'Dairy Product (Except Dried Or Canned) Merchant Wholesalers',
          'Poultry And Poultry Product Merchant Wholesalers',
          'Confectionery Merchant Wholesalers',
          'Fish And Seafood Merchant Wholesalers',
          'Meat And Meat Product Merchant Wholesalers',
          'Fresh Fruit And Vegetable Merchant Wholesalers',
          'Other Grocery And Related Products Merchant Wholesalers',
          'Grain And Field Bean Merchant Wholesalers',
          'Livestock Merchant Wholesalers',
          'Other Farm Product Raw Material Merchant Wholesalers',
          'Plastics Materials and Basic Forms and Shapes Merchant Wholesalers',
          'Other Chemical And Allied Products Merchant Wholesalers',
          'Petroleum Bulk Stations And Terminals',
          'Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)',
          'Beer And Ale Merchant Wholesalers',
          'Wine And Distilled Alcoholic Beverage Merchant Wholesalers',
          'Farm Supplies Merchant Wholesalers',
          'Book Periodical And Newspaper Merchant Wholesalers',
          "Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers",
          'Paint Varnish And Supplies Merchant Wholesalers',
          'Other Miscellaneous Nondurable Goods Merchant Wholesalers',
          'Wholesale Trade Agents and Brokers',
          'Tobacco Product and Electronic Cigarette Merchant Wholesalers',
          'Clothing and Clothing Accessories Merchant Wholesalers',
        ],
      },
      {
        industryCategory: 'Retail Trade',
        industryTypes: [
          'New Car Dealers',
          'Used Car Dealers',
          'Recreational Vehicle Dealers',
          'Boat Dealers',
          'Tire Dealers',
          'Home Centers',
          'Other Building Material Dealers',
          'Hardware Retailers',
          'Floor Covering Retailers',
          'Paint and Wallpaper Retailers',
          'Furniture Retailers',
          'Meat Retailers',
          'Convenience Retailers',
          'Gasoline Stations with Convenience Stores',
          'Optical Goods Retailers',
          'All Other Home Furnishings Retailers',
          'Food (Health) Supplement Retailers',
          'Outdoor Power Equipment Retailers',
          'Shoe Retailers',
          'Beer, Wine, and Liquor Retailers',
          'Jewelry Retailers',
          'Window Treatment Retailers',
          'Nursery, Garden Center, and Farm Supply Retailers',
          'Luggage and Leather Goods Retailers',
          'All Other Specialty Food Retailers',
          'Pharmacies and Drug Retailers',
          'Fruit and Vegetable Retailers',
          'Cosmetics, Beauty Supplies, and Perfume Retailers',
          'Automotive Parts and Accessories Retailers',
          'Baked Goods Retailers',
          'Confectionery and Nut Retailers',
          'Fish and Seafood Retailers',
          'Supermarkets and Other Grocery Retailers (except Convenience Retailers)',
          'All Other Health and Personal Care Retailers',
          'Motorcycle, ATV, and All Other Motor Vehicle Dealers',
          'Electronics and Appliance Retailers',
          'Clothing and Clothing Accessories Retailers',
        ],
      },
      {
        industryCategory:
          'Sporting Goods, Hobby, Musical Instrument, and Book Stores',
        industryTypes: [
          'Florists',
          'Art Dealers',
          'Manufactured (Mobile) Home Dealers',
          'Vending Machine Operators',
          'Fuel Dealers',
          'Book Retailers and News Dealers',
          'Office Supplies and Stationery Retailers',
          'Department Stores',
          'Warehouse Clubs and Supercenters',
          'All Other General Merchandise Retailers',
          'Used Merchandise Retailers',
          'Sporting Goods Retailers',
          'All Other Miscellaneous Retailers',
          'Hobby, Toy, and Game Retailers',
          'Sewing, Needlework, and Piece Goods Retailers',
          'Gift, Novelty, and Souvenir Retailers',
          'Pet and Pet Supplies Retailers',
          'Musical Instrument and Supplies Retailers',
        ],
      },
      {
        industryCategory: 'Transportation and Warehousing',
        industryTypes: [
          'Scheduled Passenger Air Transportation',
          'Scheduled Freight Air Transportation',
          'Nonscheduled Chartered Passenger Air Transportation',
          'Nonscheduled Chartered Freight Air Transportation',
          'Other Nonscheduled Air Transportation',
          'Line-Haul Railroads',
          'Short Line Railroads',
          'Deep Sea Freight Transportation',
          'Deep Sea Passenger Transportation',
          'Coastal And Great Lakes Freight Transportation',
          'Coastal And Great Lakes Passenger Transportation',
          'Inland Water Freight Transportation',
          'Inland Water Passenger Transportation',
          'General Freight Trucking Local',
          'General Freight Trucking Long-Distance Truckload',
          'General Freight Trucking Long-Distance Less Than Truckload',
          'Used Household And Office Goods Moving',
          'Specialized Freight (Except Used Goods) Trucking Local',
          'Specialized Freight (Ex Used Goods) Trucking Long-Distance',
          'Mixed Mode Transit Systems',
          'Commuter Rail Systems',
          'Other Urban Transit Systems',
          'Interurban And Rural Bus Transportation',
          'Limousine Service',
          'School And Employee Bus Transportation',
          'Charter Bus Industry',
          'Special Needs Transportation',
          'All Other Transit And Ground Passenger Transportation',
          'Pipeline Transportation Of Crude Oil',
          'Pipeline Transportation Of Natural Gas',
          'Pipeline Transportation Of Refined Petroleum Products',
          'All Other Pipeline Transportation',
          'Scenic And Sightseeing Transportation Land',
          'Scenic And Sightseeing Transportation Water',
          'Scenic And Sightseeing Transportation Other',
          'Air Traffic Control',
          'Other Airport Operations',
          'Other Support Activities For Air Transportation',
          'Support Activities For Rail Transportation',
          'Port And Harbor Operations',
          'Marine Cargo Handling',
          'Navigational Services To Shipping',
          'Other Support Activities For Water Transportation',
          'Motor Vehicle Towing',
          'Other Support Activities For Road Transportation',
          'Freight Transportation Arrangement',
          'Packing And Crating',
          'All Other Support Activities For Transportation',
          'Postal Service',
          'Local Messengers And Local Delivery',
          'Refrigerated Warehousing and Storage',
          'Farm Product Warehousing and Storage',
          'Other Warehousing and Storage',
          'General Warehousing and Storage',
          'Taxi and Ridesharing Services',
          'Couriers and Express Delivery Services',
          'Bus and Other Motor Vehicle Transit Systems',
        ],
      },
      {
        industryCategory: 'Information',
        industryTypes: [
          'Newspaper Publishers',
          'Periodical Publishers',
          'Book Publishers',
          'Greeting Card Publishers',
          'All Other Publishers',
          'Software Publishers',
          'Motion Picture And Video Production',
          'Motion Picture And Video Distribution',
          'Motion Picture Theaters Except Drive-Ins.',
          'Drive-In Motion Picture Theaters',
          'Teleproduction And Other Post-Production Services',
          'Other Motion Picture And Video Industries',
          'Music Publishers',
          'Sound Recording Studios',
          'Other Sound Recording Industries',
          'Satellite Telecommunications',
          'All Other Telecommunications',
          'Radio Broadcasting Stations',
          'Directory and Mailing List Publishers',
          'Record Production and Distribution',
          'Wired Telecommunications Carriers',
          'Local Exchange Carrier (Lec)',
          'Competitive Local Exchange Carrier (Clec)',
          'Long Distance Carrier - Traditional',
          'Long Distance Carrier - Emerging',
          '3rd Generation Wireless (3G)',
          'Internet Infrastructure Provider (Iip)',
          'Radio Broadcasting',
          'Internet Service Providers And Web Search Portals',
          'Television Broadcasting Stations',
          'Media Streaming Distribution Services, Social Networks, and Other Media Networks and Content Providers',
          'Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services',
          'Telecommunications Resellers',
          'Libraries and Archives',
          'Web Search Portals and All Other Information',
          'Web Search Portals and All Other Information Services',
          'Agents for Wireless Telecommunications Services',
          'Wireless Telecommunications Carriers (except Satellite)',
        ],
      },
      {
        industryCategory: 'Finance and Insurance',
        industryTypes: [
          'Monetary Authorities - Central Bank',
          'Direct Life Insurance Carriers',
          'Direct Health And Medical Insurance Carriers',
          'Direct Property And Casualty Insurance Carriers',
          'Direct Title Insurance Carriers',
          'Other Direct Insurance (Ex Life Health Medical) Carriers',
          'Reinsurance Carriers',
          'Insurance Agencies And Brokerages',
          'Claims Adjusters',
          'All Other Insurance Related Activities',
          'Pension Funds',
          'Health And Welfare Funds',
          'Other Insurance Funds',
          'Open-End Investment Funds',
          'Trusts Estates And Agency Accounts',
          'Other Financial Vehicles',
          'Pharmacy Benefit Management and Other Third Party Administration of Insurance and Pension Funds',
          'Bancassurance',
          'Government Agency',
          'Government-Sponsored Agency',
          'Savings Institutions and Other Depository Credit Intermediation',
          'Multilateral Credit Institution',
          'Composite Insurer - Predominantly Life',
          'Composite Insurer - Predominantly Non-Life',
          'Monoline Insurers',
          'Corp Pension Funds',
          'Public Pension Funds',
          'Industrywide Pension Schemes',
          'Personal & Testamentary Trusts',
          'Institutional Trusts',
          'HRF (Ucits Oe/Div 40 Act)',
          'Regulated Fds (All Other 40 ActCanadian Mutual FdsAus Fds)',
          'Other Mutual Funds (Cayman Isl Mut FdsCayman Isl Unit TrLl',
          'Closed-End Investment Funds',
          "SPV's Not Elsewhere Classified",
        ],
      },
      {
        industryCategory: 'Real Estate and Rental and Leasing',
        industryTypes: [
          'Lessors Of Residential Buildings And Dwellings',
          'Lessors Of Nonresidential Buildings (Except Miniwarehouses)',
          'Lessors Of Miniwarehouses And Self Storage Units',
          'Lessors Of Other Real Estate Property',
          'Offices Of Real Estate Agents And Brokers',
          'Residential Property Managers',
          'Nonresidential Property Managers',
          'Offices Of Real Estate Appraisers',
          'Other Activities Related To Real Estate',
          'Passenger Car Rental',
          'Passenger Car Leasing',
          'Truck Utility Trailer And Rv Rental And Leasing',
          'Consumer Electronics And Appliances Rental',
          'General Rental Centers',
          'Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing',
          'Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing',
          'Office Machinery And Equipment Rental And Leasing',
          'Other Commercial and Industrial Machinery and Equipment Rental and Leasing',
          'Formal Wear and Costume Rental',
          'Video Tape and Disc Rental',
          'Home Health Equipment Rental',
          'Recreational Goods Rental',
          'All Other Consumer Goods Rental',
          'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)',
          'Lessors Of Apartments (Leasing Of Their Own Apt)',
          'Lessors Of Industrial/Warehouses (Leasing Ind Properties)',
          'Lessors Of Offices (Leasing Their Own Office Properties)',
          'Lessors Of Retail (Renting/Leasing Own Retail Properties)',
          'Lessors Of Senior Housing/Healthcare',
          'Residential Real Estate Opportunity Funds',
          'Commercial Real Estate Opportunity Funds',
          'Equity Real Estate Investment Trust',
        ],
      },
      {
        industryCategory: 'Professional, Scientific, and Technical Services',
        industryTypes: [
          'Offices Of Lawyers',
          'Offices Of Notaries',
          'Title Abstract And Settlement Offices',
          'All Other Legal Services',
          'Offices Of Certified Public Accountants',
          'Tax Preparation Services',
          'Payroll Services',
          'Other Accounting Services',
          'Architectural Services',
          'Landscape Architectural Services',
          'Engineering Services',
          'Drafting Services',
          'Building Inspection Services',
          'Geophysical Surveying And Mapping Services',
          'Surveying And Mapping (Except Geophysical) Services',
          'Interior Design Services',
          'Industrial Design Services',
          'Graphic Design Services',
          'Other Specialized Design Services',
          'Custom Computer Programming Services',
          'Computer Systems Design Services',
          'Computer Facilities Management Services',
          'Other Computer Related Services',
          'Administrative Management and General Management Consulting Services',
          'Marketing Consulting Services',
          'Process, Physical Distribution, and Logistics Consulting Services',
          'Other Management Consulting Services',
          'Environmental Consulting Services',
          'Other Scientific And Technical Consulting Services',
          'Advertising Agencies',
          'Public Relations Agencies',
          'Media Buying Agencies',
          'Media Representatives',
          'Direct Mail Advertising',
          'Advertising Material Distribution Services',
          'Other Services Related To Advertising',
          'Marketing Research And Public Opinion Polling',
          'Photography Studios Portrait',
          'Commercial Photography',
          'Translation And Interpretation Services',
          'Veterinary Services',
          'All Other Professional Scientific And Technical Services',
          'Research and Development in Nanotechnology',
          'Research and Development in Biotechnology (except Nanobiotechnology)',
          'Research and Development in the Physical, Engineering, and Life Sciences (except Nanotechnology and Biotechnology)',
          'Research and Development in the Social Sciences and Humanities',
          'Testing Laboratories and Services',
          'Coupon Clipping Services',
          'Indoor and Outdoor Display Advertising',
          'Human Resources Consulting Services',
        ],
      },
      {
        industryCategory: 'Management of Companies and Enterprises',
        industryTypes: [
          'Offices Of Bank Holding Companies',
          'Offices Of Other Holding Companies',
          'Corporate Subsidiary And Regional Managing Offices',
        ],
      },
      {
        industryCategory:
          'Administrative and Support and Waste Management and Remediation Services',
        industryTypes: [
          'Office Administrative Services',
          'Facilities Support Services',
          'Employment Placement Agencies',
          'Executive Search Services',
          'Temporary Help Services',
          'Professional Employer Organizations',
          'Document Preparation Services',
          'Telephone Answering Services',
          'Telemarketing Bureaus and Other Contact Centers',
          'Private Mail Centers',
          'Other Business Service Centers (Including Copy Shops)',
          'Collection Agencies',
          'Credit Bureaus',
          'Repossession Services',
          'Court Reporting And Stenotype Services',
          'All Other Business Support Services',
          'Travel Agencies',
          'Tour Operators',
          'Convention And Visitors Bureaus',
          'All Other Travel Arrangement And Reservation Services',
          'Security Guards And Patrol Services',
          'Armored Car Services',
          'Security Systems Services (Except Locksmiths)',
          'Locksmiths',
          'Exterminating And Pest Control Services',
          'Janitorial Services',
          'Landscaping Services',
          'Carpet And Upholstery Cleaning Services',
          'Other Services To Buildings And Dwellings',
          'Packaging And Labeling Services',
          'Convention And Trade Show Organizers',
          'All Other Support Services',
          'Solid Waste Collection',
          'Hazardous Waste Collection',
          'Other Waste Collection',
          'Hazardous Waste Treatment And Disposal',
          'Solid Waste Landfill',
          'Solid Waste Combustors And Incinerators',
          'Other Nonhazardous Waste Treatment And Disposal',
          'Remediation Services',
          'Materials Recovery Facilities',
          'Septic Tank And Related Services',
          'All Other Miscellaneous Waste Management Services',
          'Investigation and Personal Background Check Services',
          'Secretarial Services And Company Formation Agents',
        ],
      },
      {
        industryCategory: 'Educational Services',
        industryTypes: [
          'Business And Secretarial Schools',
          'Computer Training',
          'Professional And Management Development Training',
          'Cosmetology And Barber Schools',
          'Flight Training',
          'Apprenticeship Training',
          'Other Technical And Trade Schools',
          'Fine Arts Schools',
          'Sports And Recreation Instruction',
          'Language Schools',
          'Exam Preparation And Tutoring',
          'Automobile Driving Schools',
          'All Other Miscellaneous Schools And Instruction',
          'Educational Support Services',
          'Junior Colleges',
          'Elementary And Secondary Schools (Private)',
          'Junior Colleges (Private)',
          'Colleges Universities And Professional Schools (Private)',
          'Elementary And Secondary Schools',
          'Colleges Universities And Professional Schools',
        ],
      },
      {
        industryCategory: 'Health Care and Social Assistance',
        industryTypes: [
          'Offices Of Physicians (Except Mental Health Specialists)',
          'Offices Of Physicians Mental Health Specialists',
          'Offices Of Dentists',
          'Offices Of Chiropractors',
          'Offices Of Optometrists',
          'Offices Of Mental Health Practitioners (Except Physicians)',
          'Office Of PhysicalOccupationalSpeech TherapistAudiologist',
          'Offices Of Podiatrists',
          'Offices Of All Other Miscellaneous Health Practitioners',
          'Family Planning Centers',
          'Outpatient Mental Health And Substance Abuse Centers',
          'Hmo Medical Centers',
          'Kidney Dialysis Centers',
          'Freestanding Ambulatory Surgical And Emergency Centers',
          'All Other Outpatient Care Centers',
          'Medical Laboratories',
          'Diagnostic Imaging Centers',
          'Home Health Care Services',
          'Ambulance Services',
          'Blood And Organ Banks',
          'All Other Miscellaneous Ambulatory Health Care Services',
          'General Medical And Surgical Hospitals',
          'Psychiatric And Substance Abuse Hospitals',
          'Specialty (except Psychiatric and Substance Abuse) Hospitals',
          'Residential Mental Health And Substance Abuse Facilities',
          'Continuing Care Retirement Communities',
          'Other Residential Care Facilities',
          'Child And Youth Services',
          'Services For The Elderly And Persons With Disabilities',
          'Other Individual And Family Services',
          'Community Food Services',
          'Temporary Shelters',
          'Other Community Housing Services',
          'Emergency And Other Relief Services',
          'Vocational Rehabilitation Services',
          'Resi Intellectual and Developmental Disability Facilities',
          'Child Care Services',
          'Nursing Care Facilities (Skilled Nursing Facilities)',
          'Assisted Living Facilities for the Elderly',
          'Not-For-Profit Hospitals',
          'Pharmacy Benefit Managers, Institutional Pharmacies, and Large Chain Drug Stores',
        ],
      },
      {
        industryCategory: 'Arts, Entertainment, and Recreation',
        industryTypes: [
          'Theater Companies And Dinner Theaters',
          'Dance Companies',
          'Musical Groups And Artists',
          'Other Performing Arts Companies',
          'Sports Teams And Clubs',
          'Other Spectator Sports',
          'Promoters Of Performg ArtSports&Similar Events W/Facilities',
          'Promoters Of Performg ArtSport&Similar Event W/O Facilities',
          'Independent Artists Writers And Performers',
          'Museums',
          'Historical Sites',
          'Zoos And Botanical Gardens',
          'Nature Parks And Other Similar Institutions',
          'Amusement And Theme Parks',
          'Amusement Arcades',
          'Golf Courses And Country Clubs',
          'Skiing Facilities',
          'Marinas',
          'Fitness And Recreational Sports Centers',
          'Bowling Centers',
          'All Other Amusement And Recreation Industries',
          'Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures',
        ],
      },
      {
        industryCategory: 'Accommodation and Food Services',
        industryTypes: [
          'Hotels (Except Casino Hotels) And Motels',
          'Bed And Breakfast Inns',
          'All Other Traveler Accommodation',
          'Rv (Recreational Vehicle) Parks And Campgrounds',
          'Foodservice Contractors',
          'Caterers',
          'Mobile Foodservices',
          'Drinking Places (Alcoholic Beverages)',
          'Full-Service Restaurants',
          'Limited-Service Restaurants',
          'Cafeterias Grill Buffets and Buffets',
          'Snack and Nonalcoholic Beverage Bars',
          "Rooming and Boarding Houses, Dormitories, and Workers' Camps",
          'Recreational and Vacation Camps (except Campgrounds)',
        ],
      },
      {
        industryCategory: 'Other Services (except Public Administration)',
        industryTypes: [
          'General Automotive Repair',
          'Automotive Body Paint And Interior Repair And Maintenance',
          'Automotive Glass Replacement Shops',
          'Automotive Oil Change And Lubrication Shops',
          'Car Washes',
          'All Other Automotive Repair And Maintenance',
          'C&I Machinery/Equip (Ex Auto/Electronic) Repair/Maintenance',
          'Home And Garden Equipment Repair And Maintenance',
          'Appliance Repair And Maintenance',
          'Reupholstery And Furniture Repair',
          'Footwear And Leather Goods Repair',
          'Other Personal And Household Goods Repair And Maintenance',
          'Barber Shops',
          'Beauty Salons',
          'Nail Salons',
          'Diet And Weight Reducing Centers',
          'Other Personal Care Services',
          'Cemeteries And Crematories',
          'Coin-Operated Laundries And Drycleaners',
          'Drycleaning And Laundry Services (Except Coin-Operated)',
          'Linen Supply',
          'Industrial Launderers',
          'Pet Care (Except Veterinary) Services',
          'Photo Finishing Laboratories (Except One-Hour)',
          'One-Hour Photo Finishing',
          'Parking Lots And Garages',
          'All Other Personal Services',
          'Private Households',
          'Funeral Homes & Funerial Services',
          'Electronic and Precision Equipment Repair and Maintenance',
          'Adult Oriented Other than Media',
          'Adult Oriented Media',
          'Specialized Automotive Repair',
        ],
      },
      {
        industryCategory: 'Public Administration',
        industryTypes: [
          'Administration of Conservation Programs',
          'Executive Offices',
          'Legislative Bodies',
          'Executive And Legislative Offices Combined',
          'American Indian And Alaska Native Tribal Governments',
          'Courts',
          'Police Protection',
          'Legal Counsel And Prosecution',
          'Correctional Institutions',
          'Parole Offices And Probation Offices',
          'Fire Protection',
          'Administration Of Education Programs',
          'Administration Of Public Health Programs',
          "Administration Of Veteran'S Affairs",
          'Administration of Air and Water Resource and Solid Waste Management Programs',
          'Administration Of Housing Programs',
          'Admin Of Urban Planning And Community & Rural Develop',
          'Administration Of General Economic Programs',
          'Regulation and Administration of Transportation Programs',
          'Regulation and Administration of Communications, Electric, Gas, and Other Utilities',
          'Regulation Of Agricultural Marketing And Commodities',
          'Regulation Licensing Inspection Of Misc Commercial Sectors',
          'Space Research And Technology',
          'National Security',
          "Administration of Human Resource Programs (except Education, Public Health, and Veterans' Affairs Programs)",
          'Other General Government Support',
          'Central Government',
          'Public Finance (Finance Ministries Treasury)',
          'Water Waste Water And Solid Waste Mgmt (Public Utilities)',
          'Surface Transportation And Facilities (Roads Rail Subway)',
          'Airport (Transportation)',
          'Electricity Utilities (Public Utilities)',
          'Other Central Government',
          'Municipal Airport',
          'Electrical Cooperative',
          'Municipality Owned Electrical Utilities',
          'City Or County Owned Hospitals',
          'Other Justice, Public Order, and Safety Activities',
          'Public Finance Activities',
        ],
      },
    ],
  };
  