export const getClientMock = {
  attestations: [],
  id: '3000000333',
  createdAt: '2022-11-18T12:28:11.232Z',
  parties: [
    {
      id: '2000000555',
      partyType: 'ORGANIZATION',
      externalId: 'TC1234',
      email: 'contact@example.com',
      profileStatus: 'INFORMATION_REQUESTED',
      roles: ['CLIENT'],
      active: true,
      organizationDetails: {
        organizationType: 'LIMITED_LIABILITY_COMPANY',
        organizationName: 'Top Cookies',
        dbaName: 'Top Cookies NYC',
        organizationDescription:
          'Every morning, we freshly bake the hottest cookies that will warm your heart.',
        industryCategory: 'Retail Trade',
        industryType: 'Baked Goods Store',
        countryOfFormation: 'US',
        yearOfFormation: '2020',
        significantOwnership: true,
        entitiesInOwnership: false,
        addresses: [
          {
            addressType: 'BUSINESS_ADDRESS',
            addressLines: ['90 Bedford Street', 'Apt 2E'],
            city: 'New York',
            state: 'NY',
            postalCode: '10014',
            country: 'US',
          },
        ],
        phone: {
          phoneType: 'BUSINESS_PHONE',
          countryCode: '+1',
          phoneNumber: '6316215110',
        },
        organizationIds: [
          {
            idType: 'EIN',
            issuer: 'US',
            value: '000000001',
          },
        ],
        websiteAvailable: true,
        website: 'https://topcookie.net',
      },
    },
    {
      partyType: 'INDIVIDUAL',
      email: 'controller@company.com',
      roles: ['CONTROLLER'],
      parentPartyId: '2000000000',
      products: ['EMBEDDED_PAYMENTS'],
      individualDetails: {
        countryOfResidence: 'US',
        firstName: 'Bob',
        middleName: 'Headman',
        lastName: 'Smith',
        birthDate: '1997-10-10',
        individualIds: [
          {
            idType: 'SSN',
            value: '998889999',
            issuer: 'US',
            expiryDate: '2029-01-06',
          },
        ],
        phone: {
          phoneType: 'BUSINESS_PHONE',
          phoneNumber: '1010101010',
          countryCode: 'US',
        },
        addresses: [
          {
            addressType: 'RESIDENTIAL_ADDRESS',
            addressLines: [
              '689 Main St',
              'Opposite St. Andrews Church',
              'Mini York',
            ],
            city: 'Anchorage',
            county: 'Santa Clara',
            state: 'CA',
            postalCode: '99501',
            country: 'US',
          },
        ],
        soleOwner: true,
      },
    },
  ],
  partyId: '2000000555',
  platformId: '6000000333',
  products: ['EMBEDDED_PAYMENTS'],
  outstanding: {
    attestationDocumentIds: ['09f60565-3820-482c-b4e4-2d2b40494d6a'],
    documentRequestIds: [],
    partyIds: [],
    partyRoles: ['CONTROLLER', 'BENEFICIAL_OWNER'],
    questionIds: ['30001', '30002', '30003'],
  },
  questionResponses: [],
  status: 'NEW',
  results: {
    customerIdentityStatus: 'NOT_STARTED',
  },
};
