// This code sample generated by GitHub Copilot demonstrates how to sign a payload using a private key and the RS256 algorithm.

const fs = require('fs');
const jsrsasign = require('jsrsasign');

try {
    const privateKey = fs.readFileSync('certs/jpmc-signature.key').toString();

    const header = { "alg": "RS256" };
    const sHeader = JSON.stringify(header);
    const requestData = JSON.stringify(requestDataJSON);

    const jws = jsrsasign.jws.JWS.sign(header.alg, sHeader, requestData, privateKey);
    console.log(jws);
} catch (error) {
    console.error('Could not create signature. Error:', error.message);
}

