# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test SDK

on:
  push:
    paths:
      - "app/client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
        working-directory: ./app/client
      - name: Build
        run: yarn build
        working-directory: ./app/client
      - name: Run tests
        run: yarn run test:no-watch
        working-directory: ./app/client
